version: '3.7'
services:
  user_activities_db:
    image: mysql:8.0.33
    container_name: user_activities_db
#    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: root
#      MYSQL_USER: root
#      MYSQL_PASSWORD: root
      MYSQL_DATABASE: user_activities
      MYSQL_TCP_PORT: 3307
    volumes:
#      - ./src/main/resources/data.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql

    networks:
      - springboot-mysql-network
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      retries: 10
      interval: 3s
      timeout: 30s
  user_activities:
    build: .
    restart: no
    container_name: user_activities
    ports:
      - "8090:8090"
    depends_on:
      user_activities_db:
        condition: service_healthy
    environment:
      DB_HOST: user_activities_db
      DB_PORT: 3307
      DB_NAME: user_activities
      DB_USERNAME: root
      DB_PASSWORD: root
      SERVER_PORT: 8090
    networks:
      - springboot-mysql-network
# Volumes
volumes:
  mysql-data:
# Networks
networks:
  springboot-mysql-network:
    name: springboot-mysql-network
